import numpy as np
import os
import json
import hashlib
from typing import Dict, Optional, Tuple

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

from utils.logger import get_logger

logger = get_logger(__name__)


class TFLiteConverter:
    """
    企业级TensorFlow Lite模型转换器。

    功能:
    - Keras .h5 → .tflite 转换
    - 动态范围量化 (FP16)
    - 全整数量化 (INT8) + 代表性数据集
    - 模型优化 (pruning, clustering)
    - C头文件生成 (用于ESP32固件集成)
    - 模型元数据管理与校验
    """

    def __init__(self, model_dir: str = 'deployment/models'):
        self.model_dir = model_dir
        os.makedirs(model_dir, exist_ok=True)

    def convert_keras_to_tflite(
        self,
        model_path: str,
        output_name: str = 'model',
        optimization: str = 'dynamic',
        representative_data: Optional[np.ndarray] = None
    ) -> Tuple[str, Dict]:
        """
        将Keras .h5模型转换为TFLite格式。

        Args:
            model_path: Keras模型路径
            output_name: 输出文件名（不含扩展名）
            optimization: 优化类型 'none' | 'dynamic' | 'float16' | 'int8'
            representative_data: INT8量化所需的代表数据集

        Returns:
            (输出文件路径, 转换信息字典)
        """
        import tensorflow as tf

        logger.info("Converting %s to TFLite (optimization=%s)", model_path, optimization)

        converter = tf.lite.TFLiteConverter.from_keras_model_file(model_path)

        if optimization == 'dynamic':
            converter.optimizations = [tf.lite.Optimize.DEFAULT]
        elif optimization == 'float16':
            converter.optimizations = [tf.lite.Optimize.DEFAULT]
            converter.target_spec.supported_types = [tf.float16]
        elif optimization == 'int8':
            converter.optimizations = [tf.lite.Optimize.DEFAULT]
            if representative_data is not None:
                def representative_dataset():
                    for i in range(min(len(representative_data), 100)):
                        yield [representative_data[i:i+1].astype(np.float32)]
                converter.representative_dataset = representative_dataset
            converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
            converter.inference_input_type = tf.int8
            converter.inference_output_type = tf.int8

        tflite_model = converter.convert()

        output_path = os.path.join(
            self.model_dir, f"{output_name}_{optimization}.tflite"
        )
        with open(output_path, 'wb') as f:
            f.write(tflite_model)

        model_size_kb = len(tflite_model) / 1024

        info = {
            'source': model_path,
            'output': output_path,
            'optimization': optimization,
            'model_size_kb': round(model_size_kb, 2),
            'sha256': self._compute_sha256(tflite_model)
        }

        logger.info("TFLite conversion complete: %s (%.1f KB)", output_path, model_size_kb)
        return output_path, info

    def generate_c_header(
        self,
        tflite_path: str,
        output_header: str,
        array_name: str = 'vibration_model',
        align_size: int = 16
    ):
        """
        生成C头文件，用于ESP32固件集成。

        生成格式对齐 ESP-IDF TensorFlow Lite Micro 要求:
        - 使用 alignas(algin_size) 对齐
        - 使用 const unsigned char 数组
        - 同时导出长度常量

        Args:
            tflite_path: TFLite模型文件路径
            output_header: 输出C头文件路径
            array_name: 数组变量名
            align_size: 内存对齐大小
        """
        with open(tflite_path, 'rb') as f:
            model_data = f.read()

        model_size = len(model_data)
        lines = []

        lines.append('/* Auto-generated by EdgeVib TFLiteConverter */')
        lines.append(f'/* Source: {os.path.basename(tflite_path)} */')
        lines.append(f'/* Size: {model_size} bytes */')
        lines.append(f'/* SHA256: {self._compute_sha256(model_data)} */')
        lines.append('')
        lines.append('#ifndef __EDGEVIB_MODEL_DATA_H')
        lines.append('#define __EDGEVIB_MODEL_DATA_H')
        lines.append('')
        lines.append('#include <stdint.h>')
        lines.append('#include <stdalign.h>')
        lines.append('')
        lines.append(f'#define {array_name.upper()}_LEN {model_size}')
        lines.append('')
        lines.append(f'alignas({align_size}) static const unsigned char {array_name}[] = {{')

        hex_bytes = []
        for i in range(0, model_size, 12):
            chunk = model_data[i:min(i+12, model_size)]
            hex_line = ', '.join(f'0x{b:02x}' for b in chunk)
            hex_bytes.append(f'  {hex_line}')

        lines.append(',\n'.join(hex_bytes))
        lines.append('};')
        lines.append('')
        lines.append(f'#endif /* __EDGEVIB_MODEL_DATA_H */')

        os.makedirs(os.path.dirname(output_header), exist_ok=True)
        with open(output_header, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

        logger.info("C header generated: %s (%d bytes)", output_header, model_size)

    def benchmark_tflite(
        self,
        tflite_path: str,
        test_data: np.ndarray,
        num_runs: int = 100
    ) -> Dict:
        """
        TFLite模型性能基准测试。

        Args:
            tflite_path: TFLite模型路径
            test_data: 测试数据 (1, window_size, features)
            num_runs: 测试运行次数

        Returns:
            基准测试结果字典
        """
        import tensorflow as tf
        import time

        interpreter = tf.lite.Interpreter(model_path=tflite_path)
        interpreter.allocate_tensors()

        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()

        if test_data.ndim == 2:
            test_data = np.expand_dims(test_data, axis=0)

        interpreter.set_tensor(input_details[0]['index'], test_data.astype(np.float32))

        interpreter.invoke()
        _ = interpreter.get_tensor(output_details[0]['index'])

        times = []
        for _ in range(num_runs):
            start = time.perf_counter()
            interpreter.set_tensor(input_details[0]['index'], test_data.astype(np.float32))
            interpreter.invoke()
            _ = interpreter.get_tensor(output_details[0]['index'])
            times.append((time.perf_counter() - start) * 1000)

        times = np.array(times)
        result = {
            'mean_latency_ms': round(float(np.mean(times)), 3),
            'median_latency_ms': round(float(np.median(times)), 3),
            'p95_latency_ms': round(float(np.percentile(times, 95)), 3),
            'p99_latency_ms': round(float(np.percentile(times, 99)), 3),
            'min_latency_ms': round(float(np.min(times)), 3),
            'max_latency_ms': round(float(np.max(times)), 3),
            'num_runs': num_runs,
            'input_shape': list(input_details[0]['shape']),
            'output_shape': list(output_details[0]['shape'])
        }

        logger.info(
            "TFLite benchmark: mean=%.2fms, p95=%.2fms",
            result['mean_latency_ms'], result['p95_latency_ms']
        )
        return result

    def compare_accuracy(
        self,
        keras_model_path: str,
        tflite_path: str,
        test_data: np.ndarray
    ) -> Dict:
        """
        对比Keras和TFLite模型的精度差异。

        Args:
            keras_model_path: Keras模型路径
            tflite_path: TFLite模型路径
            test_data: 测试数据

        Returns:
            精度对比结果
        """
        import tensorflow as tf

        keras_model = tf.keras.models.load_model(keras_model_path)
        keras_pred = keras_model.predict(test_data, verbose=0)

        interpreter = tf.lite.Interpreter(model_path=tflite_path)
        interpreter.allocate_tensors()
        input_details = interpreter.get_input_details()
        output_details = interpreter.get_output_details()

        tflite_preds = []
        for i in range(len(test_data)):
            x = test_data[i:i+1].astype(np.float32)
            interpreter.set_tensor(input_details[0]['index'], x)
            interpreter.invoke()
            tflite_preds.append(interpreter.get_tensor(output_details[0]['index'])[0])

        tflite_preds = np.array(tflite_preds)

        mae = float(np.mean(np.abs(keras_pred - tflite_preds)))
        max_diff = float(np.max(np.abs(keras_pred - tflite_preds)))

        keras_classes = np.argmax(keras_pred, axis=1)
        tflite_classes = np.argmax(tflite_preds, axis=1)
        agreement = float(np.mean(keras_classes == tflite_classes))

        result = {
            'mae': round(mae, 6),
            'max_absolute_diff': round(max_diff, 6),
            'classification_agreement': round(agreement, 4)
        }

        logger.info(
            "Accuracy comparison: MAE=%.6f, Agree=%.2f%%",
            mae, agreement * 100
        )
        return result

    def _compute_sha256(self, data: bytes) -> str:
        return hashlib.sha256(data).hexdigest()
